import {createHash} from 'node:crypto';

// Pure. Given a selection it returns the exact file tree to commit, so the
// checksum is reproducible and the archive can be byte-stable. No timestamps,
// no randomness, no network.

export const PLUGIN='satchel-skills';
export const MARKETPLACE='satchel-kit';
export const TARGETS=['claude-code','codex'];
// Written on every publish and never deleted, so neither target owns them.
export const SHARED=['README.md','.claude-plugin/marketplace.json','.agents/plugins/marketplace.json'];
const json=value=>JSON.stringify(value,null,2)+'\n';
const owner={name:'Satchel'};

function readme(repository) {
  return `# Satchel kit

\`skills/\` is yours. Edit \`skills/<name>/SKILL.md\` directly, or let your agent
edit it. Satchel reads that directory and never rewrites it when publishing.

Everything else here is generated by Satchel and is replaced on the next
publish. Do not edit it by hand.

## Install

Claude Code:

    claude plugin marketplace add ${repository}
    claude plugin install ${PLUGIN}@${MARKETPLACE}

Codex:

    codex plugin marketplace add ${repository}

then install ${PLUGIN} from the Plugins Directory.

## Update

    claude plugin marketplace update ${MARKETPLACE}
    codex plugin marketplace upgrade ${MARKETPLACE}
`;
}

// Each host reads only its own marketplace file, listing only its own plugin
// directory. A directory that has never been published is left out, because an
// entry pointing at a missing path is at best skipped and at worst fatal.
function claudeMarketplace(live) {
  return json({name:MARKETPLACE,owner,description:'Your Satchel skills.',
    plugins:live.includes('claude-code')?[{name:PLUGIN,source:'./claude-code',
      description:'Your Satchel skills for Claude Code.'}]:[]});
}
function codexMarketplace(live) {
  return json({name:MARKETPLACE,interface:{displayName:'Satchel kit'},
    plugins:live.includes('codex')?[{name:PLUGIN,source:{source:'local',path:'./codex'},
      policy:{installation:'AVAILABLE',authentication:'ON_INSTALL'},category:'Productivity'}]:[]});
}

// No mcp.json, no .mcp.json, no .app.json anywhere: OpenAI marks any plugin
// declaring MCP servers as Desktop only, which would restrict every skill here.
function manifest(target,version) {
  const common={name:PLUGIN,version:`0.0.${version}`,author:owner};
  if(target==='claude-code')
    return {'claude-code/.claude-plugin/plugin.json':json({...common,
      description:'Your Satchel skills for Claude Code.'})};
  return {'codex/plugin.json':json({
    $schema:'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
    ...common,description:'Your Satchel skills for Codex.',
    extensions:{'com.openai':{interface:{displayName:'Satchel skills',
      shortDescription:'Your own skills, selected in Satchel.',
      developerName:'Satchel',category:'Productivity'}}},
  })};
}

export function buildRelease({target,version,repository,skills,liveTargets}) {
  if(!TARGETS.includes(target))throw Error(`Unsupported target: ${target}`);
  if(!Number.isInteger(version)||version<1)throw Error('Version must be a positive integer');
  const live=[...new Set([...(liveTargets??[]),target])].filter(t=>TARGETS.includes(t));
  const files={
    'README.md':readme(repository),
    '.claude-plugin/marketplace.json':claudeMarketplace(live),
    '.agents/plugins/marketplace.json':codexMarketplace(live),
    ...manifest(target,version),
  };
  const seen=new Set();
  for(const skill of skills) {
    if(seen.has(skill.name))throw Error(`Duplicate skill in kit: ${skill.name}`);
    seen.add(skill.name);
    // Content passes through verbatim. Rewriting it would make the delivered
    // skill differ from its source, which is the one thing this design forbids.
    files[`${target}/skills/${skill.name}/SKILL.md`]=skill.content;
  }
  const generatedPaths=Object.keys(files).sort();
  return {files,generatedPaths,checksum:checksum(files)};
}

export function checksum(files) {
  const hash=createHash('sha256');
  // Sorted paths and explicit byte lengths keep this free of key-order and
  // delimiter ambiguity.
  for(const path of Object.keys(files).sort()) {
    const body=Buffer.from(files[path],'utf8');
    hash.update(path,'utf8');hash.update('\0');
    hash.update(String(body.byteLength),'utf8');hash.update('\0');
    hash.update(body);
  }
  return hash.digest('hex');
}

// Only paths under this target's own prefix may be removed. Shared files are
// rewritten, never deleted, and nothing outside the prefix is touched, which is
// what keeps a publish from deleting the user's own skills/ directory.
// existingPaths comes from the live tree, so this is exact rather than bookkept.
export function deletions({existingPaths=[],generatedPaths,target}) {
  if(!TARGETS.includes(target))throw Error(`Unsupported target: ${target}`);
  const keep=new Set(generatedPaths);
  const prefix=`${target}/`;
  return existingPaths.filter(path=>path.startsWith(prefix)&&!keep.has(path)).sort();
}

export function targetPrefix(target) {
  if(!TARGETS.includes(target))throw Error(`Unsupported target: ${target}`);
  return `${target}/`;
}
