const { chromium } = require('playwright');
const out = {};
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1900, height: 1150 } });
  const errors = []; page.on('pageerror', e => errors.push('page: ' + e.message));
  page.on('console', m => { if (m.type() === 'error' && !/404/.test(m.text())) errors.push('console: ' + m.text()); });
  await page.goto('http://localhost:8765/jeff-companion.html');
  await page.getByRole('button', { name: 'Play interactive artboard' }).click();
  await page.waitForTimeout(1500);
  const f = page.frames().find(fr => fr !== page.mainFrame() && fr.url().startsWith('about:')) || page.frames()[1];
  await f.locator('.hw').first().waitFor({ timeout: 10000 });
  const tab = async (n) => { await f.locator('.tab', { hasText: n }).click(); await page.waitForTimeout(250); };
  const txt = async (sel) => (await f.locator(sel).first().textContent()).trim();
  out.rail = await txt('text=/SYNCED/');
  await tab('Settings');
  out.repoShown = await f.locator('.mono:has-text("neerajg03/hub")').count();
  await f.locator('.key', { hasText: 'Disconnect' }).click(); await page.waitForTimeout(250);
  out.railNoRepo = await txt('text=/NO REPO/');
  await tab('Book');
  out.noRepoNote = await f.locator('text=/No repo connected/').count();
  const li = f.locator('input.line').first(); await li.fill('should fail'); await li.press('Enter'); await page.waitForTimeout(250);
  out.saveBlocked = await f.locator('text=/Couldn.t reach GitHub/').count();
  out.draftKept = await li.inputValue();
  await f.locator('.key', { hasText: 'Connect a repo' }).click(); await page.waitForTimeout(250);
  const ri = f.locator('input.line.mono').first(); await ri.fill('neerajg03/second-brain'); await f.locator('.key', { hasText: 'Grant access' }).click(); await page.waitForTimeout(250);
  out.newRepo = await f.locator('.mono:has-text("neerajg03/second-brain")').count();
  out.tree = await f.locator('.pre:has-text("npx skills add neerajg03/second-brain")').count();
  await tab('Book');
  await li.fill('Committed line'); await li.press('Enter'); await page.waitForTimeout(250);
  out.shaShown = await f.locator('.meta.new').first().textContent();
  await f.locator('span.act:has-text("History")').nth(2).click(); await page.waitForTimeout(200);
  out.historyPath = await f.locator('text=/memory\\/you\\/plain-language.md/').count();
  await tab('Apps');
  await f.locator('.key', { hasText: 'Run the check' }).first().click(); await page.waitForTimeout(200);
  out.checkLabel = await f.locator('text=/GitHub reachable/').count();
  await f.locator('.tab', { hasText: 'Settings' }).click(); await page.waitForTimeout(200);
  await f.locator('.key', { hasText: 'Show the book as text' }).click(); await page.waitForTimeout(200);
  out.exportRepoHeader = await f.locator('.pre:has-text("memory/ ·")').count();
  await f.locator('.hwkey', { hasText: 'More' }).click(); await page.waitForTimeout(150);
  await f.locator('.rowbtn', { hasText: 'Settings' }).click(); await page.waitForTimeout(200);
  out.phoneRepo = await f.locator('.hw .mono:has-text("neerajg03/second-brain")').count();
  await f.locator('.tab', { hasText: 'Projects' }).click(); await page.waitForTimeout(250);
  out.projectRepos = await f.locator('.mono:has-text("neerajg03/reimbursements")').count();
  const pi = f.locator('input.line').first(); await pi.fill('Hermes'); await pi.press('Enter'); await page.waitForTimeout(250);
  out.newProjectRepo = await f.locator('.mono:has-text("neerajg03/hermes")').count();
  await page.screenshot({ path: 'pw-repo.png' });
  out.errors = errors; console.log(JSON.stringify(out, null, 2)); await browser.close();
})().catch(e => { console.error('FAIL', e.message.split('\n')[0]); console.error(JSON.stringify(out, null, 2)); process.exit(1); });
